### ISSUE TITLE
Support storing bytes

### ISSUE THREAD

**Issue by dvzubarev** [torden/py-mdbm#45]
Hi, thank you for this package.
When trying to store byte-string:
`dbm.store(b"key2", b"binary vale", mdbm.MDBM_INSERT)`
I get following error:
`mdbm.Error: Error - There was a missing parameter: key and value` from  [here](https://github.com/torden/py-mdbm/blob/3977f2dd03643aaf75e514a8c298ffae465a0b0a/src/libmdbm.c#L981).
It would be good if byte-strings were supported too.

**Comment by torden** [comment]
Hi @dvzubarev 
I will take this issue. (too late)

**Comment by torden** [comment]
Hi @dvzubarev 
Support the Byte Key and Value on Now. 
Let me know if you find any issues.
Plz feel free~

**Comment by torden** [comment]
Hi @dvzubarev 
I was add byte storing feature
Could you plz check up laster version?
if you have any issue, plz feel free raise issue

**Comment by dvzubarev** [comment]
Hi, Thank you for working on this!
I used my fork as workaround for some time in my project. I will switch to the latest version, when start working on this project again. But it may take some time. Thank you again.

**Comment by torden** [comment]
Hi, @dvzubarev 
it's my pleasure.
If you have any questions or concerns, don’t hesitate to let me know.
Thanks & Best regards.
